# Global config
cl.config.log_level = "info"

[nodes.validator1]
[nodes.validator2]
[nodes.validator3]
[nodes.validator4]
[nodes.validator5]
[nodes.validator6]
[nodes.validator7]
start_at = 10

[nodes.full1]
[nodes.full2]
start_at = 20

[nodes.full3]
start_at = 10
