// Copyright 2025 Circle Internet Group, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::path::PathBuf;

use clap::Args;

use crate::{
    accounts::PartitionMode,
    config::{Erc20FnWeights, GuzzlerFnWeights, TxTypeMix},
    Config,
};

#[derive(Debug, Clone, Args)]
pub struct SpammerArgs {
    /// Number of transaction generators to run in parallel
    ///
    /// A higher number of generators helps increase the transaction rate.
    /// Each generator will manage a subset of the accounts, so there won't
    /// be nonce collisions generated by different generators.
    #[clap(short = 'g', long, default_value = "1", global = true)]
    pub num_generators: usize,
    /// Maximum number of genesis accounts used to sign transactions
    ///
    /// The number of accounts in the genesis file must be equal or higher
    /// than this number. A higher value helps decrease the risk of nonce
    /// gaps. The genesis file must be generated with a sufficient number of
    /// extra prefunded accounts. Check out the `--num-extra-accounts`
    /// argument of the `setup` command.
    #[clap(short = 'a', long, default_value = "100", global = true)]
    pub max_num_accounts: usize,
    /// How to partition the account space among generators (linear or
    /// exponential)
    ///
    /// Linear mode: the space is divided equally between generators.
    ///
    /// Exponential mode: each generator takes half of the unassigned space
    /// until there's no more space unassigned. The generator with the
    /// higher number of the accounts will reuse the same account less
    /// often, thus reducing the probability of having nonce conflicts for
    /// those accounts. Generators handling a small range of accounts will
    /// reuse those accounts very frequently, thus reaching higher nonce
    /// values for those accounts.
    #[clap(
        short = 'm',
        long,
        value_enum,
        default_value_t = PartitionMode::Linear,
        global = true
    )]
    pub partition_mode: PartitionMode,
    /// Maximum total number of transactions to send (0 for no limit)
    #[clap(short = 'n', long, default_value = "0", global = true)]
    pub num_txs: u64,
    /// Number of transactions to send per second (all generators combined)
    #[clap(short = 'r', long, default_value = "1000", global = true, value_parser = clap::value_parser!(u64).range(1..))]
    pub rate: u64,
    /// Maximum time in seconds to send transactions (applies to all generators) (0 for no limit)
    #[clap(short = 't', long, default_value = "0", global = true)]
    pub time: u64,
    /// Size of transaction input data in bytes
    #[clap(short = 's', long, default_value = "0", global = true)]
    pub tx_input_size: usize,
    /// Maximum number of transactions to send per account (0 for no limit)
    ///
    /// A low value helps reduce the risk of nonce gaps. A high value will
    /// take more time to initialise accounts.
    #[clap(short = 'x', long, default_value = "0", global = true)]
    pub max_txs_per_account: u64,
    /// Pre-initialize accounts with their signing keys and latest nonces
    /// (default is to lazily initialize each account).
    ///
    /// By default, each account is initialised on the fly just before
    /// sending the first transaction, which reduces the transaction rate.
    #[clap(short = 'i', long, default_value = "false", global = true)]
    pub preinit_accounts: bool,
    /// Whether to query nodes for the latest nonce of each account before sending the first transaction (may choke RPC endpoints) or start from nonce=0 (faster).
    ///
    /// Finding out the latest nonce of an account requires one RPC call to each target node.
    #[clap(short = 'l', long, default_value = "false", global = true)]
    pub query_latest_nonce: bool,
    /// Output the status of all Reth tx-pools (number of pending and queued transactions)
    #[clap(
        short = 'p',
        long,
        default_value = "false",
        visible_alias = "pools",
        global = true
    )]
    pub show_pool_status: bool,
    /// Record submit-to-finalized latency to a CSV file.
    ///
    /// This mode records the time when a transaction is submitted via
    /// `eth_sendRawTransaction` and the time when it is observed in a
    /// block via `eth_subscribe("newHeads")`.
    #[clap(long, default_value = "false", global = true)]
    pub tx_latency: bool,
    /// Directory for the latency CSV file.
    ///
    /// Defaults to the current directory when omitted.
    /// Can only be used when `--tx-latency` is enabled.
    #[clap(long, requires = "tx_latency", global = true)]
    pub csv_dir: Option<PathBuf>,
    /// Wait for the response from Reth after sending a transaction
    ///
    /// If false, the output will only show the number of transactions sent and its length in bytes.
    /// If true, the output will additionally show error messages if any, but it will slow down the execution.
    #[clap(short = 'w', long, default_value = "false", global = true)]
    pub wait_response: bool,
    /// Number of reconnection attempts when a connection fails
    #[clap(long, default_value = "3", global = true)]
    pub reconnect_attempts: u32,
    /// Time to wait between reconnection attempts (e.g., "3s", "500ms")
    #[clap(
        long,
        default_value = "3s",
        value_parser = humantime::parse_duration,
        global = true
    )]
    pub reconnect_period: std::time::Duration,
    /// Weighted transaction type mix.
    ///
    /// Format: transfer=50,legacy=20,erc20=20,guzzler=10
    /// Omitted types default to weight 0 (disabled).
    /// When omitted, defaults based on --guzzler-fn-weights:
    ///   if guzzler functions enabled: 100% guzzler;
    ///   otherwise: 100% transfer.
    #[clap(long = "mix", global = true)]
    pub tx_type_mix: Option<TxTypeMix>,
    /// Weighted function mix and per-function argument for GasGuzzler calls.
    ///
    /// Format: hash-loop=70@2000,storage-write=30@600,storage-read=0,guzzle=0,guzzle2=0
    /// Omitted functions default to weight 0 (disabled), so "hash-loop=100@2000" is valid.
    /// If total weight is 0, transfer transactions are used.
    #[clap(
        long = "guzzler-fn-weights",
        default_value = "hash-loop=0,storage-write=0,storage-read=0,guzzle=0,guzzle2=0",
        global = true
    )]
    pub guzzler_fn_weights: GuzzlerFnWeights,
    /// Weighted function mix for ERC-20 calls.
    ///
    /// Format: transfer=70,approve=20,transfer-from=10
    /// Omitted functions default to weight 0 (disabled).
    /// When omitted (all weights 0), ERC-20 uses 100% transfer.
    #[clap(long = "erc20-fn-weights", global = true)]
    pub erc20_fn_weights: Option<Erc20FnWeights>,
}

impl SpammerArgs {
    pub fn to_config(&self, silent: bool, fire_and_forget: bool) -> Config {
        // Resolve tx_type_mix: explicit --mix takes precedence, otherwise
        // infer from --guzzler-fn-weights for backward compatibility.
        let tx_type_mix = self.tx_type_mix.unwrap_or_else(|| {
            if self.guzzler_fn_weights.total_weight() > 0 {
                TxTypeMix {
                    guzzler: 100,
                    ..Default::default()
                }
            } else {
                TxTypeMix {
                    transfer: 100,
                    ..Default::default()
                }
            }
        });

        // Resolve erc20_fn_weights: explicit --erc20-fn-weights takes precedence, otherwise
        // default to 100% transfer for backward compatibility.
        let erc20_fn_weights = self.erc20_fn_weights.unwrap_or(Erc20FnWeights {
            transfer: 100,
            ..Default::default()
        });

        Config {
            num_generators: self.num_generators,
            partition_mode: self.partition_mode,
            max_num_accounts: self.max_num_accounts,
            preinit_accounts: self.preinit_accounts,
            query_latest_nonce: self.query_latest_nonce,
            max_num_txs: self.num_txs,
            max_rate: self.rate,
            max_time: self.time,
            tx_input_size: self.tx_input_size,
            max_txs_per_account: self.max_txs_per_account,
            silent,
            show_pool_status: self.show_pool_status,
            tx_latency: self.tx_latency,
            wait_response: self.wait_response,
            reconnect_attempts: self.reconnect_attempts,
            reconnect_period: self.reconnect_period,
            tx_type_mix,
            guzzler_fn_weights: self.guzzler_fn_weights,
            erc20_fn_weights,
            csv_dir: self.csv_dir.clone(),
            fire_and_forget,
        }
    }
}
