[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
solc = "0.8.23"
ffi = true

# Fork da Polygon Mainnet para testes com estado real
rpc_endpoints = { polygon = "https://polygon-mainnet.g.alchemy.com/v2/gYZF24lug9plNntuHQL9h" }

# Remappings para forge-std
remappings = [
    "@forge-std/=C:/lib/forge-std/src/",
]
