// Copyright 2026 Circle Internet Group, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::collections::HashSet;
use std::sync::LazyLock;

/// Flags managed by Docker Compose that cannot be overridden via manifests.
static RESERVED_EL_FLAGS: LazyLock<HashSet<&'static str>> = LazyLock::new(|| {
    HashSet::from([
        "--authrpc.addr",
        "--authrpc.port",
        "--authrpc.jwtsecret",
        "--auth-ipc",
        "--auth-ipc.path",
        "--datadir",
        "--chain",
        "--http.port",
        "--http.addr",
        "--http.corsdomain",
        "--ipcdisable",
        "--ipcpath",
        "--metrics",
        "--ws.port",
        "--ws.addr",
        "--ws.origins",
        // This flag is managed by the compose template to point to the
        // corresponding CL container.
        "--arc-rpc-upstream-url",
        // Log file settings are managed by the compose template.
        "--log.file.directory",
        "--log.file.max-files",
        // Nodekeys and trusted peers are generated by quake's setup step.
        "--p2p-secret-key",
        "--trusted-peers",
        // Pprof bind address is managed by the binary default (0.0.0.0)
        // and should not be overridden via manifests.
        "--pprof.addr",
    ])
});

/// Flag to enable the HTTP-RPC server in the EL.
/// Note: this is our custom key. Reth uses `--http` to enable HTTP,
/// but in quake's manifests we use `http.enable = true` to comply with TOML syntax.
const EL_HTTP_ENABLE_FLAG: &str = "http.enable";
/// Flag to enable the WS-RPC server in the EL.
/// Note: this is our custom key. Reth uses `--ws` to enable WS,
/// but in quake's manifests we use `ws.enable = true` to comply with TOML syntax.
const EL_WS_ENABLE_FLAG: &str = "ws.enable";
/// Flag for the log level in EL configuration.
/// Note: this is our custom key. Reth uses `-v`, `-vv`, etc. to set the log level,
/// but in quake's manifests we use `log.level = "info"` for clarity.
/// Therefore, we do the mapping from `log.level` to `-v` flags in the conversion
/// function below.
const EL_LOG_FLAG: &str = "log.level";

/// Converts a TOML table of EL configuration to CLI flags.
///
/// Flattens nested keys with `.` separator and converts values:
/// - `flag = true` → `--flag`
/// - `flag = false` → (omitted)
/// - `http.enable = true` → `--http` (special case, suffix stripped)
/// - `ws.enable = true` → `--ws` (special case, suffix stripped)
/// - `flag = 123` → `--flag=123`
/// - `flag = "value"` → `--flag=value`
/// - Nested tables are flattened: `http.port = 8545` → `--http.port=8545`
///
/// The `.enable` suffix is stripped only for `http` and `ws` flags, allowing
/// these boolean flags to coexist with nested config in TOML. Other flags
/// like `era.enable` keep the suffix intact.
///
/// # Example
/// ```ignore
/// let table = toml::toml! {
///     http.enable = true
///     http.port = 8545
///     txpool.nolocals = true
/// };
/// let flags = el_config_to_cli_flags(&table);
/// // Result: ["--http", "--http.port=8545", "--txpool.nolocals"]
/// ```
pub(crate) fn el_config_to_cli_flags(table: &toml::Table) -> Vec<String> {
    let mut flags = Vec::new();
    flatten_toml_to_flags(table, String::new(), &mut flags);
    flags
}

/// Removes Docker Compose-managed flags from CLI flags list.
///
/// These flags are defined in the Docker Compose template and should not
/// be overridable via manifests. Any matching flags are silently ignored.
pub(crate) fn filter_reserved_flags(flags: Vec<String>) -> Vec<String> {
    flags
        .into_iter()
        .filter(|flag| {
            let key = flag.split('=').next().unwrap_or(flag);
            !RESERVED_EL_FLAGS.contains(key)
        })
        .collect()
}

/// Converts a string to kebab-case.
///
/// Replaces underscores with hyphens and inserts hyphens before uppercase
/// letters (converting camelCase/PascalCase to kebab-case), then lowercases
/// the result.
fn to_kebab_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    for (i, ch) in s.char_indices() {
        if ch == '_' {
            result.push('-');
        } else if ch.is_uppercase() {
            if i > 0 {
                result.push('-');
            }
            result.extend(ch.to_lowercase());
        } else {
            result.push(ch);
        }
    }
    result
}

/// Recursively flattens a TOML table into CLI flags.
///
/// TOML parses dotted keys like `http.port = 8545` into nested tables:
/// `{ http: { port: 8545 } }`. This function walks the nested structure,
/// accumulating key segments in `prefix` to reconstruct the original
/// dotted key (e.g., `"http" + "port"` → `"http.port"` → `"--http.port=8545"`).
/// Each key segment is converted to kebab-case.
fn flatten_toml_to_flags(table: &toml::Table, prefix: String, flags: &mut Vec<String>) {
    for (key, value) in table {
        // Build the full dotted key by joining prefix with current key,
        // converting each key segment to kebab-case.
        // Example: prefix="http", key="port" → full_key="http.port"
        let kebab_key = to_kebab_case(key);
        let full_key = if prefix.is_empty() {
            kebab_key
        } else {
            format!("{}.{}", prefix, kebab_key)
        };

        match value {
            toml::Value::Table(nested) => {
                flatten_toml_to_flags(nested, full_key, flags);
            }
            toml::Value::Boolean(b) => {
                // arc.builder.wait-for-payload is the only boolean that defaults to
                // true, so it must be explicitly set to false in the manifest for
                // it to be disabled.
                // For all other booleans, we follow the common convention of
                // emitting a flag only when the value is true, and omitting it when
                // false.
                // NOTE: if we have more booleans with non-false defaults in the
                // future, we may want to refactor this logic to use a list of
                // "explicit" booleans that require `--key=true/false`, instead of
                // hardcoding the every special case.
                if full_key.eq("arc.builder.wait-for-payload") {
                    flags.push(format!("--{}={}", full_key, b));
                    return;
                }
                // Other booleans: true = flag present, false = omit
                if *b {
                    let flag_key = match full_key.as_str() {
                        // Strip ".enable" suffix for http and ws flags only.
                        EL_HTTP_ENABLE_FLAG => "http",
                        EL_WS_ENABLE_FLAG => "ws",
                        // `-d` is an alias for `--disable-discovery` in reth.
                        "d" => "disable-discovery",
                        _ => &full_key,
                    };
                    flags.push(format!("--{}", flag_key));
                }
            }
            toml::Value::String(s) => {
                if full_key == EL_LOG_FLAG {
                    let verbosity = match s.as_str() {
                        "error" => "v",
                        "warning" => "vv",
                        "info" => "vvv",
                        "debug" => "vvvv",
                        "trace" => "vvvvv",
                        _ => "vvv", // default to info
                    };
                    flags.push(format!("-{}", verbosity));
                    return;
                }
                flags.push(format!("--{}={}", full_key, s));
            }
            toml::Value::Integer(i) => {
                flags.push(format!("--{}={}", full_key, i));
            }
            toml::Value::Float(f) => {
                flags.push(format!("--{}={}", full_key, f));
            }
            toml::Value::Array(arr) => {
                // When TOML input is an array like `http.api = ["admin", "net"]`,
                // join elements with comma: --http.api=admin,net
                let joined: Vec<String> = arr
                    .iter()
                    .map(|v| match v {
                        toml::Value::String(s) => s.clone(),
                        _ => v.to_string(),
                    })
                    .collect();
                if !joined.is_empty() {
                    flags.push(format!("--{}={}", full_key, joined.join(",")));
                }
            }
            // reth doesn't use timestamp flags, but we put this here for the
            // completeness of the match statement.
            toml::Value::Datetime(dt) => {
                flags.push(format!("--{}={}", full_key, dt));
            }
        }
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_to_kebab_case() {
        use super::to_kebab_case;

        assert_eq!(to_kebab_case("hello"), "hello");
        assert_eq!(to_kebab_case("hello_world"), "hello-world");
        assert_eq!(to_kebab_case("helloWorld"), "hello-world");
        assert_eq!(to_kebab_case("HelloWorld"), "hello-world");
        assert_eq!(to_kebab_case("nolocals"), "nolocals");
        assert_eq!(
            to_kebab_case("persistenceThreshold"),
            "persistence-threshold"
        );
        assert_eq!(to_kebab_case("already-kebab"), "already-kebab");
    }

    #[test]
    fn test_kebab_case_key_conversion() {
        use super::el_config_to_cli_flags;

        // snake_case and camelCase keys should be converted to kebab-case
        let mut table = toml::Table::new();
        table.insert("persistence_threshold".to_string(), toml::Value::Integer(5));
        table.insert("noLocals".to_string(), toml::Value::Boolean(true));
        let flags = el_config_to_cli_flags(&table);

        assert!(flags.contains(&"--persistence-threshold=5".to_string()));
        assert!(flags.contains(&"--no-locals".to_string()));
    }

    #[test]
    fn test_toml_table_to_cli_flags_bool() {
        use super::el_config_to_cli_flags;

        let table = toml::toml! {
            txpool.nolocals = true
            disable-discovery = false
        };
        let flags = el_config_to_cli_flags(&table);

        assert!(flags.contains(&"--txpool.nolocals".to_string()));
        assert!(!flags.iter().any(|f| f.contains("disable-discovery")));
    }

    #[test]
    fn test_toml_table_d_alias() {
        use super::el_config_to_cli_flags;

        let table = toml::toml! {
            d = true
        };
        let flags = el_config_to_cli_flags(&table);
        assert!(flags.iter().any(|f| f.contains("disable-discovery")));
    }

    #[test]
    fn test_toml_table_to_cli_flags_enable_suffix() {
        use super::el_config_to_cli_flags;

        // http.enable and ws.enable get suffix stripped → --http, --ws
        // era.enable keeps suffix → --era.enable
        let table = toml::toml! {
            http.enable = true
            http.port = 8545
            ws.enable = true
            ws.port = 8546
            era.enable = true
        };
        let flags = el_config_to_cli_flags(&table);

        // http.enable → --http (suffix stripped)
        assert!(flags.contains(&"--http".to_string()));
        assert!(!flags.iter().any(|f| f == "--http.enable"));
        assert!(flags.contains(&"--http.port=8545".to_string()));

        // ws.enable → --ws (suffix stripped)
        assert!(flags.contains(&"--ws".to_string()));
        assert!(!flags.iter().any(|f| f == "--ws.enable"));
        assert!(flags.contains(&"--ws.port=8546".to_string()));

        // era.enable → --era.enable (suffix kept)
        assert!(flags.contains(&"--era.enable".to_string()));
    }

    #[test]
    fn test_toml_table_to_cli_flags_with_values() {
        use super::el_config_to_cli_flags;

        let table = toml::toml! {
            http.port = 8545
            builder.deadline = 10
            metrics = "0.0.0.0:9001"
        };
        let flags = el_config_to_cli_flags(&table);

        assert!(flags.contains(&"--http.port=8545".to_string()));
        assert!(flags.contains(&"--builder.deadline=10".to_string()));
        assert!(flags.contains(&"--metrics=0.0.0.0:9001".to_string()));
    }

    #[test]
    fn test_toml_table_to_cli_flags_array() {
        use super::el_config_to_cli_flags;

        let table = toml::toml! {
            // both of these are valid ways to set up an array of strings
            // reth_default.toml uses the first because it's cleaner.
            http.api = ["admin", "net", "eth"]
            ws.api = "admin,net,eth"
        };
        let flags = el_config_to_cli_flags(&table);

        assert!(flags.contains(&"--http.api=admin,net,eth".to_string()));
        assert!(flags.contains(&"--ws.api=admin,net,eth".to_string()));
    }

    #[test]
    fn test_toml_table_to_cli_flags_empty() {
        use super::el_config_to_cli_flags;

        let table = toml::Table::new();
        let flags = el_config_to_cli_flags(&table);

        assert!(flags.is_empty());
    }

    #[test]
    fn test_filter_reserved_flags() {
        use super::filter_reserved_flags;

        let flags = vec![
            "--http".to_string(),
            "--http.port=8545".to_string(),
            "--http.addr=0.0.0.0".to_string(),
            "--http.api=admin,net,eth".to_string(),
            "--ws.port=8546".to_string(),
            "--ws.addr=0.0.0.0".to_string(),
            "--metrics=0.0.0.0:9001".to_string(),
            "--authrpc.port=8551".to_string(),
            "--ipcdisable".to_string(),
            "--log.file.directory=/var/log/arc".to_string(),
            "--log.file.max-files=5".to_string(),
            "--p2p-secret-key=/data/nodekey".to_string(),
            "--trusted-peers=enode://abc@1.2.3.4:30303".to_string(),
            "--pprof.addr=0.0.0.0:6061".to_string(),
            "--txpool.nolocals".to_string(),
            "--disable-discovery".to_string(),
        ];
        let filtered = filter_reserved_flags(flags);

        // Reserved flags should be removed
        assert!(!filtered.iter().any(|f| f.contains("--http.port=8545")));
        assert!(!filtered.iter().any(|f| f.contains("--http.addr=0.0.0.0")));
        assert!(!filtered.iter().any(|f| f.contains("--ws.port=8546")));
        assert!(!filtered.iter().any(|f| f.contains("--ws.addr=0.0.0.0")));
        assert!(!filtered
            .iter()
            .any(|f| f.contains("--metrics=0.0.0.0:9001")));
        assert!(!filtered.iter().any(|f| f.contains("--authrpc.port=8551")));
        assert!(!filtered.iter().any(|f| f.contains("--ipcdisable")));
        assert!(!filtered.iter().any(|f| f.contains("--log.file.directory")));
        assert!(!filtered.iter().any(|f| f.contains("--log.file.max-files")));
        assert!(!filtered.iter().any(|f| f.contains("--p2p-secret-key")));
        assert!(!filtered.iter().any(|f| f.contains("--trusted-peers")));
        assert!(!filtered.iter().any(|f| f.contains("--pprof.addr")));

        // Non-reserved flags should remain
        assert!(filtered.contains(&"--http".to_string()));
        assert!(filtered.contains(&"--http.api=admin,net,eth".to_string()));
        assert!(filtered.contains(&"--txpool.nolocals".to_string()));
        assert!(filtered.contains(&"--disable-discovery".to_string()));
    }

    #[test]
    fn test_log_level_conversion() {
        use super::el_config_to_cli_flags;

        // creates the TOML table:
        // { "log": { "level": "<level>" } }
        fn table_with_log_level(level: &str) -> toml::Table {
            let mut log = toml::Table::new();
            log.insert("level".to_string(), toml::Value::String(level.to_string()));

            let mut table = toml::Table::new();
            table.insert("log".to_string(), toml::Value::Table(log));
            table
        }

        let cases = [
            ("error", "-v"),
            ("warning", "-vv"),
            ("info", "-vvv"),
            ("debug", "-vvvv"),
            ("trace", "-vvvvv"),
            ("invalid", "-vvv"),
        ];

        for (level, expected) in cases {
            let table = table_with_log_level(level);
            let flags = el_config_to_cli_flags(&table);
            assert_eq!(
                flags,
                vec![expected.to_string()],
                "unexpected verbosity for log.level={level}",
            );
        }
    }

    #[test]
    fn test_arc_builder_bool_emits_explicit_value() {
        use super::el_config_to_cli_flags;

        let table = toml::toml! {
            arc.builder.wait-for-payload = false
        };
        let flags = el_config_to_cli_flags(&table);
        assert!(
            flags.contains(&"--arc.builder.wait-for-payload=false".to_string()),
            "false should emit --key=false, got: {flags:?}"
        );

        let table = toml::toml! {
            arc.builder.wait-for-payload = true
        };
        let flags = el_config_to_cli_flags(&table);
        assert!(
            flags.contains(&"--arc.builder.wait-for-payload=true".to_string()),
            "true should emit --key=true, got: {flags:?}"
        );
    }

    #[test]
    fn test_arc_builder_bool_absent_when_unset() {
        use super::el_config_to_cli_flags;

        let table = toml::toml! {
            arc.builder.deadline = 300
        };
        let flags = el_config_to_cli_flags(&table);
        assert!(
            !flags.iter().any(|f| f.contains("wait-for-payload")),
            "absent field should produce no flag, got: {flags:?}"
        );
    }
}
