# APT retry configuration for CI reliability
# - Retries: number of retry attempts for failed downloads (with exponential backoff)
# - ForceIPv4: avoid IPv6 connectivity issues in some CI environments
Acquire::Retries "10";
Acquire::ForceIPv4 "true";
