// Copyright 2026 Circle Internet Group, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use alloy_primitives::map::HashMap;
use clap::ValueEnum;
use color_eyre::eyre::{bail, eyre, Result, WrapErr};
use indexmap::IndexMap;
use serde::de::Error as _;
use serde::{Deserialize, Deserializer, Serialize};
use std::fmt;
use std::{fs, path::Path};

use crate::manifest::{self, RemoteKeyId};
use crate::node::{Container, ContainerName, IpAddress, NodeName, SubnetName};
use crate::nodes::NodeOrContainerName;

pub(crate) mod docker;
pub(crate) mod export;
pub(crate) mod local;
pub(crate) mod remote;
pub(crate) mod ssm;
pub(crate) mod terraform;

pub(crate) const COMPOSE_PROJECT_NAME: &str = "arc_testnet";

pub(crate) const INFRA_DATA_FILENAME: &str = "infra-data.json";

const PROMETHEUS_PORT: u16 = 9090;
const GRAFANA_PORT: u16 = 3000;
const BLOCKSCOUT_PORT: u16 = 80;

// Use ports >1024: AWS SSM can only bind to ports <1024 when the client process runs as root.
const PROMETHEUS_SSM_PORT: u16 = 19090;
const GRAFANA_SSM_PORT: u16 = 13000;
const BLOCKSCOUT_SSM_PORT: u16 = 8000;

// RPC Proxy port on CC for routing RPC requests to nodes
pub(crate) const RPC_PROXY_PORT: u16 = 8080;
pub(crate) const RPC_PROXY_SSM_PORT: u16 = 18080;

// Pprof Proxy port on CC for routing pprof requests to nodes
const PPROF_PROXY_PORT: u16 = 6060;
pub(crate) const PPROF_PROXY_SSM_PORT: u16 = 16060;

#[derive(Debug, Default, Copy, Clone, ValueEnum)]
pub(crate) enum BuildProfile {
    Dev,
    #[default]
    Release,
    Profiling,
}

impl fmt::Display for BuildProfile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.to_possible_value()
            .expect("no values are skipped")
            .get_name()
            .fmt(f)
    }
}

/// Types of infrastructure providers.
#[derive(Debug, Clone, Copy, ValueEnum, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum InfraType {
    Local,
    Remote,
}

/// Infrastructure provider.
pub(crate) trait InfraProvider: Send + Sync + std::any::Any {
    /// Build the binaries and/or Docker images needed to run the nodes.
    fn build(&self, profile: BuildProfile) -> Result<()>;

    /// Is the infrastructure set up and ready to run the testnet?
    fn is_setup(&self, nodes: &[NodeName]) -> Result<()>;

    /// Start the given node names or container names, or the whole testnet if no targets are given.
    fn start(&self, targets: &[NodeOrContainerName]) -> Result<()>;

    /// Stop the given node names or container names, or the whole testnet if no targets are given.
    fn stop(&self, targets: &[NodeOrContainerName]) -> Result<()>;

    /// Stop and remove the given node names or container names, or the whole testnet if no targets are given.
    fn down(&self, targets: &[NodeOrContainerName]) -> Result<()>;

    /// Show the logs of the given containers, or all containers if none are given.
    /// Optionally following the logs
    fn logs(&self, containers: &[NodeOrContainerName], follow: bool) -> Result<()>;

    /// Disconnect the given containers from their subnets.
    fn disconnect(&self, containers_subnets: &[(&Container, &[&SubnetName])]) -> Result<()>;

    /// Connect the given containers to their subnets.
    fn connect(&self, containers_subnets: &[(&Container, &[&SubnetName])]) -> Result<()>;

    /// Kill the given container names.
    fn kill(&self, containers: &[ContainerName]) -> Result<()>;

    /// Pause the given container names.
    fn pause(&self, containers: &[ContainerName]) -> Result<()>;

    /// Unpause the given container names.
    fn unpause(&self, containers: &[ContainerName]) -> Result<()>;

    /// Restart the given container names.
    fn restart(&self, containers: &[ContainerName]) -> Result<()>;
}

/// Note: In remote mode, this struct is populated from infra-data.json, generated by the Terraform scripts.
#[derive(Debug, Deserialize, Serialize, Clone)]
pub(crate) struct InfraData {
    project_name: String,
    #[serde(rename = "provider")]
    pub infra_type: InfraType,
    pub control_center: Option<NodeInfraData>,
    pub nodes: IndexMap<String, NodeInfraData>,
}

impl InfraData {
    pub fn new(
        dir: &Path,
        testnet_name: String,
        nodes: &IndexMap<String, manifest::Node>,
        force_remote: bool,
    ) -> Result<Self> {
        let infra_data_path = &dir.join(INFRA_DATA_FILENAME);
        // Use remote mode if we are forced to or there exists an infra data file; otherwise fall back to local mode.
        let infra_data = if infra_data_path.exists() {
            let data = InfraData::from_file(infra_data_path)?;
            // Validate infra data file against manifest
            if data.num_nodes() != nodes.len() {
                bail!("Number of nodes in infra data ({}) does not match number of nodes in manifest ({})", data.num_nodes(), nodes.len());
            }
            // Ensure every manifest node exists in infra data (same scenario / same node set)
            let missing: Vec<_> = nodes
                .keys()
                .filter(|name| !data.nodes.contains_key(*name))
                .cloned()
                .collect();
            if !missing.is_empty() {
                bail!(
                    "Infra data does not match the manifest: {} node(s) missing from {} (e.g. '{}')",
                    missing.len(),
                    infra_data_path.display(),
                    missing.first().map(String::as_str).unwrap_or(""),
                );
            }
            data
        } else if force_remote {
            InfraData::new_remote(testnet_name.clone())
        } else {
            InfraData::new_local(testnet_name.clone(), nodes)
        };
        Ok(infra_data)
    }

    /// Build infra data from file (remote only).
    pub fn from_file(file: &Path) -> Result<Self> {
        // Serialize infra data from file
        let content = fs::read_to_string(file)
            .with_context(|| format!("Failed to read infra data from {file:?}"))?;
        let mut infra_data: InfraData = serde_json::from_str(&content)
            .with_context(|| format!("Failed to parse infra data from {file:?}"))?;

        // Assign local ports to be used by SSM tunnels to remote ports in CC
        let cc = infra_data
            .control_center
            .as_mut()
            .ok_or_else(|| eyre!("Invalid infra data: missing control_center in {file:?}"))?;
        let ssm_tunnel_ports = cc.ssm_tunnel_ports.get_or_insert_with(HashMap::default);
        ssm_tunnel_ports.insert(PROMETHEUS_PORT, PROMETHEUS_SSM_PORT);
        ssm_tunnel_ports.insert(GRAFANA_PORT, GRAFANA_SSM_PORT);
        ssm_tunnel_ports.insert(BLOCKSCOUT_PORT, BLOCKSCOUT_SSM_PORT);
        ssm_tunnel_ports.insert(RPC_PROXY_PORT, RPC_PROXY_SSM_PORT);
        ssm_tunnel_ports.insert(PPROF_PROXY_PORT, PPROF_PROXY_SSM_PORT);

        Ok(infra_data)
    }

    pub fn new_local(
        project_name: String,
        manifest_nodes: &IndexMap<String, manifest::Node>,
    ) -> Self {
        let mut nodes = IndexMap::new();
        for (i, (name, node)) in manifest_nodes.iter().enumerate() {
            nodes.insert(
                name.to_string(),
                NodeInfraData {
                    public_ip: "127.0.0.1".to_string(),
                    instance_id: None,
                    ssm_tunnel_ports: None,
                    // CL and EL need to use different IP address ranges to avoid conflicts when running locally.
                    // In NodeMetadata we replace the "x" with the actual value.
                    subnet_ips: IndexMap::from([(
                        manifest::DEFAULT_SUBNET_NAME.to_string(),
                        format!("172.19.x.{}", i),
                    )]),
                    remote_signer: node.remote_signer,
                },
            );
        }
        Self {
            project_name,
            infra_type: InfraType::Local,
            control_center: None,
            nodes,
        }
    }

    fn new_remote(project_name: String) -> Self {
        Self {
            project_name,
            infra_type: InfraType::Remote,
            control_center: None,
            nodes: IndexMap::new(),
        }
    }

    pub fn num_nodes(&self) -> usize {
        self.nodes.len()
    }

    pub fn node_names(&self) -> Vec<&NodeName> {
        self.nodes.keys().collect::<Vec<_>>()
    }

    pub fn max_node_name_len(&self) -> Option<usize> {
        self.nodes.keys().map(|name| name.len()).max()
    }

    pub fn max_public_ip_len(&self) -> Option<usize> {
        self.nodes.iter().map(|(_, n)| n.public_ip.len()).max()
    }

    pub fn get_data(&self, node_name: &str) -> Result<&NodeInfraData> {
        if node_name == remote::CC_INSTANCE {
            self.control_center
                .as_ref()
                .ok_or_else(|| eyre!("Control Center data not found"))
        } else {
            self.nodes
                .get(node_name)
                .ok_or_else(|| eyre!("Node {node_name} not found"))
        }
    }

    /// Local testnets expose these services directly. Remote testnets expose
    /// them through the Control Center SSM forwards instead.
    pub fn monitoring_ports(&self) -> (u16, u16, u16) {
        match self.infra_type {
            InfraType::Local => (PROMETHEUS_PORT, GRAFANA_PORT, BLOCKSCOUT_PORT),
            InfraType::Remote => (PROMETHEUS_SSM_PORT, GRAFANA_SSM_PORT, BLOCKSCOUT_SSM_PORT),
        }
    }
}

/// Note: In remote mode, this struct is populated from infra-data.json, generated by the Terraform scripts.
#[derive(Debug, Deserialize, Serialize, Clone)]
pub(crate) struct NodeInfraData {
    pub public_ip: IpAddress,
    pub instance_id: Option<String>,
    // Mapping of remote to local ports for SSM tunnels (remote mode only).
    pub ssm_tunnel_ports: Option<HashMap<u16, u16>>,
    /// Map of subnet name to private IP for that subnet.
    /// Bridge nodes have multiple entries (one per ENI/network).
    /// Guaranteed non-empty by the custom deserializer.
    #[serde(deserialize_with = "deserialize_non_empty_indexmap")]
    subnet_ips: IndexMap<SubnetName, IpAddress>,
    /// Use the remote signing service for this node
    pub remote_signer: Option<RemoteKeyId>,
}

impl NodeInfraData {
    /// Returns the AWS instance ID, or an error if running in local mode.
    pub fn instance_id(&self) -> Result<String> {
        self.instance_id
            .as_ref()
            .ok_or_else(|| eyre!("Instance ID not found"))
            .cloned()
    }

    pub fn subnet_ips(&self) -> &IndexMap<SubnetName, IpAddress> {
        &self.subnet_ips
    }

    /// The first subnet IP in map order (primary ENI in remote mode), used for SSH and routing.
    pub fn first_private_ip(&self) -> &IpAddress {
        self.subnet_ips
            .values()
            .next()
            .expect("subnet_ips is guaranteed non-empty by construction")
    }
}

fn deserialize_non_empty_indexmap<'de, D, K, V>(
    deserializer: D,
) -> std::result::Result<IndexMap<K, V>, D::Error>
where
    D: Deserializer<'de>,
    K: Deserialize<'de> + std::hash::Hash + Eq,
    V: Deserialize<'de>,
{
    let map = IndexMap::<K, V>::deserialize(deserializer)?;
    if map.is_empty() {
        return Err(D::Error::custom("expected at least one subnet_ips entry"));
    }
    Ok(map)
}
